### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by ghost** [dpploy/danae#14]
It would be useful to build a test suite for dados using `pytest` similar to the one used in cortix to make sure each commit passes at least a few sanity checks

**Comment by dealmeidavf** [comment]
Agreed. Sphinx doc/ should be in the project plans. We need to add pytest
to the list in the repo plans so it gets done.

**Comment by seamuss1** [comment]
This feature has been added. Thank you for the suggestion to improve dados
