### ISSUE TITLE
Error with writing header to file

### ISSUE THREAD

**Issue by seamuss1** [dpploy/danae#23]
https://github.com/dpploy/dados/blob/master/dados.py
In dados.py, line 94, there is a mistake in the way the header is written to the file. A whole bunch of extraneous tabs are included in the code, after the new line. This causes formatting issues especially when reading to pandas dataframes. The corrected code is at included at the bottom, but it would be easier to just keep it on one line.
```

f.write('Date and Time, Type, Callback, Status Group,\
ch1_rate_filtered, ch1_rate_unfiltered, ch1_dose,\
ch1_alarm_high, ch1_alarm_low, ch2_rate_filtered,\
ch2_rate_unfiltered, ch2_dose, ch2_alarm_high,\
ch2_alarm_low, Leak Rate: Gallons/Day,\
Leak Rate: %Power Level, ch3_rate_filtered,\
ch3_rate_unfiltered, ch3_dose, ch3_alarm_high,\
ch3_alarm_low, ch4_rate_filtered, ch4_rate_unfiltered,\
ch4_dose, ch4_alarm_high, ch4_alarm_low, Probe_status,\
Checksum\n')

```

**Comment by dealmeidavf** [comment]
Everything  below [this line](https://github.com/dpploy/dados/blob/b86d859027977c8fe1c2a6f69e71a0dd4916463c/dados.py#L86) needs to be reviewed including the write statement which should go into a data frame or something else similar.
